version: '3'
services:
  app:
    image: sendmail
    restart: always
    extra_hosts:
      - "smtp.exmail.qq.com:163.177.90.125"
    environment:
      - "GO_ENV=test"
      - "SERVER_LOG=/data/logs/mail/mail.log"
      - "REDIS_ADDRESS=localhost:6379"
      - "MAIL_HOST=smtp.exmail.qq.com"
      - "MAIL_PORT=465"
      - "MAIL_SENDER=pangxieke@126.com"
      - "MAIL_PWD=***"
    container_name: mail
    volumes:
      - /data/logs/mail:/data/logs/mail
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
networks:
  default:
    external:
      name: test_default
